// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-ho1s8ko8KwAKhfRQtar03oga3Mw15jw',
    appId: '1:435373855093:web:12fbaecab4d1b4a087c33c',
    messagingSenderId: '435373855093',
    projectId: 'app-cripto-8dcaa',
    authDomain: 'app-cripto-8dcaa.firebaseapp.com',
    storageBucket: 'app-cripto-8dcaa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANqTIXUrEPcoFTN0BbAw_medmrPUH_n7g',
    appId: '1:435373855093:android:02ffc28e6ca67dc887c33c',
    messagingSenderId: '435373855093',
    projectId: 'app-cripto-8dcaa',
    storageBucket: 'app-cripto-8dcaa.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-ho1s8ko8KwAKhfRQtar03oga3Mw15jw',
    appId: '1:435373855093:web:4ee8fc5f5362aa4a87c33c',
    messagingSenderId: '435373855093',
    projectId: 'app-cripto-8dcaa',
    authDomain: 'app-cripto-8dcaa.firebaseapp.com',
    storageBucket: 'app-cripto-8dcaa.firebasestorage.app',
  );
}
